// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqpjqyjyidyargswfzga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxcGpxeWp5aWR5YXJnc3dmemdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzIyNDIsImV4cCI6MjA3MDU0ODI0Mn0.7WDWaJCvxEdmX4U62KawHvxmwTZaPfR7UdHyX8oEHq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});